### ISSUE TITLE
Previously good 10.8.1 Template failing on deployment

### ISSUE THREAD

**Issue by PapachoSneak** [Esri/arcgis-azure-templates#11]
We're having an issue when attempting to re-deploy our environment from known good templates that we previously deployed from (late fall 2021).  The specific template we're using is adding an additional ArcGIS Server deployment to an existing Enterprise deployment (the Enterprise deployment still worked).  When we run the add server deployment, the template seems to validate properly and the deployment starts, but after a few minutes it fails on the "appGatewayNestedDeployment" step.  The specific error we're seeing is:

"{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"ApplicationGatewayPropertyNotSupportedApiVersionTooOld","message":"Specified api-version '2019-04-01' does not support property 'Priority' in context '/subscriptions/0db291ed-24cd-4525-bf7e-7c52045f6685/resourceGroups/navyazint/providers/Microsoft.Network/applicationGateways/entAppGateway/requestRoutingRules/entHttpToHttpsEnterpriseRequestRoutingRule'. Use at least api-version '2019-07-01' or remove property 'Priority' from the request body."}]}"

Again, this exact deployment worked fine late last fall.  We're not sure what has changed, or how to get past this error.  

Please advise?  Thanks!

**Comment by johnholistic** [comment]
Having same issue, is this a new bug in the ARM Template?

**Comment by shailesh91** [comment]
@tigerhobbs thanks for your contribution. I have merged your PR. @PapachoSneak and @johnholistic - updating the api version should fix the issue.
