### ISSUE TITLE
Where can I find the Wiki

### ISSUE THREAD

**Issue by MiguelElGallo** [Esri/arcgis-azure-templates#15]
Hello,
The readme.md reads:
`See wiki pages for more information about using ArcGIS Azure Resource Manager (ARM) Templates.`
Can you please let me know the link to that wiki?

We need some guidance how to use this Repo, for example

Which the main file to run?
Is it [deployAzureResourceGroup.sh](https://github.com/Esri/arcgis-azure-templates/blob/master/Releases/11.0/deployAzureResourceGroup.sh) and then use as template https://github.com/Esri/arcgis-azure-templates/blob/master/Releases/11.0/Templates/gisserver-multi-tier.json

Thanks!

**Comment by nshampur** [comment]
Here you go 
https://github.com/Esri/arcgis-azure-templates/wiki

**Comment by MiguelElGallo** [comment]
Thanks!
