### ISSUE TITLE
Deployment failure when attempting to use domain account for ArcGIS Service Account

### ISSUE THREAD

**Issue by PapachoSneak** [Esri/arcgis-azure-templates#5]
We're attempting to build an Image Server deployment which is both joined to an existing domain, and use a domain account for the ArcGIS Service account.  We have previously successfully deployed to the domain when using a non-domain account for the ArcGIS Service Account, but when we change that to a domain account and re-deploy a new site, we get the following failure message:

.....] Deploy-AzureResourceGroup.ps1 : Template deployment returned the following errors:  
4:39:11 PM - The deployment 'azuredeploy-0520-2021' failed with error(s). Showing 1 out of 1 error(s).
Status Message: VM has reported a failure when processing extension 'DSCConfiguration0'. Error message: "DSC Configuration  
'GISServerSingleTierConfiguration' completed with error(s). Following are the first few: Logon failure: the user has not    
been granted the requested logon type at this computer The SendConfigurationApply function did not succeed."
More information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot
(Code:VMExtensionProvisioningError)
CorrelationId: dfb049d3-cedc-4cc1-9a52-30752dec8ca3
At C:\Users\[....]\Deploy-ArcGISSite.ps1:33 char:1
+ .\Deploy-AzureResourceGroup.ps1 -StorageAccountName $StorageAccountNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-AzureResourceGroup.ps1

Testing after the error message is thrown, we see:

- The ArcGIS Windows services are configured properly using the domain account, and the service is running
- The ArcGIS processes (ArcGISServer, ArcSOC, etc.) are all running
- Manager comes up on the localhost URL
- Manager shows the proper directory locations and machine in the site
- Manager shows **no web adaptors**
- The Azure App Gateway reports the backend pool as unhealthy (in Details it says "The CA of the certificate used by the backed server is invalid....."
- The URL to hit the Image Server through App Gateway (https://our.dns.alias/image/manager) returns a **502 Bad Gateway** error.

It feels like the configuration is failing when trying to register the App Gateway / Web Adaptor, and is reporting that the domain user doesn't have some kind of permission set?  Again this same deployment works if we use the non-domain account "arcgis" as the ArcGIS Service Account, so it makes us strongly suspect that it's something with this user.

Please let me know what additional information I can provide?

**Comment by shailesh91** [comment]
@PapachoSneak looks like your domain controller is enforcing some user management capabilities. And can you please check if the run as account - arcgis exists as part of your AD?

**Comment by PapachoSneak** [comment]
Thanks @shailesh91 .  Checking with out IT folks now about the user management capabilities and will report back.  

For your question about the run as account - do you mean the ArcGIS Service account?
![image](https://user-images.githubusercontent.com/34924787/119177561-780e3a80-ba3a-11eb-9417-3bdbabc7834b.png)
If so, yes - it's in AD, and it authenticates and starts the services.  I didn't take a screenshot of that before I tore it back down, but it did show up in the Services control panel on the server VM - the domain account had started the service and it was running fine.  So the failure happened after that part of the automation.

**Comment by PapachoSneak** [comment]
Hey @shailesh91 .  You were right - our IT folks found that the service account we were using was in a group that explicitly denies the right to logon locally:
![image](https://user-images.githubusercontent.com/34924787/119195941-6d13d400-ba53-11eb-8d77-41d8208458d9.png)
They moved the account out of that group and the deployment worked without error.  Thanks for your help on this!
